_target_: kernellib.features.config.create_spatiotemporal_coords

lon_min: 295.0 # domain min longitude
lon_max: 305.0 # domain max longitude
dx_lon: 0.2 # zonal grid spatial step (in degree)
lat_min: 33.0 # domain min latitude
lat_max: 43.0 # domain max latitude
dx_lat: 0.2 # meridional grid spatial step (in degree)

time_min: "2017-01-01"
time_max: "2017-12-31"
dt_step: 1
dt_period: "D"