
train_data_dir: "/bettik/johnsonj/data/data_challenges/ssh_mapping_2021/train/*.nc"
test_data_dir: "/bettik/johnsonj/data/data_challenges/ssh_mapping_2021/test/"
test_data_filename: "dt_gulfstream_c2_phy_l3_20161201-20180131_285-315_23-53.nc"
ref_data_dir: "/bettik/johnsonj/data/data_challenges/ssh_mapping_2021/ref/"
ref_data_filename: "mdt.nc"
results_dir: "/bettik/johnsonj/data/data_challenges/ssh_mapping_2021/results/"
results_filename: "OSE_ssh_mapping.nc"
stats_dir: "/bettik/johnsonj/data/data_challenges/ssh_mapping_2021/interim"
logs_dir: "/bettik/johnsonj/data/data_challenges/ssh_mapping_2021/logs/"
name: "gricad"